package com.ccc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEmail<M extends BaseEmail<M>> extends Model<M> implements IBean {

	public M setEmailId(java.lang.Integer emailId) {
		set("email_id", emailId);
		return (M)this;
	}
	
	public java.lang.Integer getEmailId() {
		return getInt("email_id");
	}

	public M setEmailEmail(java.lang.String emailEmail) {
		set("email_email", emailEmail);
		return (M)this;
	}
	
	public java.lang.String getEmailEmail() {
		return getStr("email_email");
	}

	public M setEmailNickname(java.lang.String emailNickname) {
		set("email_nickname", emailNickname);
		return (M)this;
	}
	
	public java.lang.String getEmailNickname() {
		return getStr("email_nickname");
	}

	public M setEmailPass(java.lang.String emailPass) {
		set("email_pass", emailPass);
		return (M)this;
	}
	
	public java.lang.String getEmailPass() {
		return getStr("email_pass");
	}

	public M setEmailCode(java.lang.String emailCode) {
		set("email_code", emailCode);
		return (M)this;
	}
	
	public java.lang.String getEmailCode() {
		return getStr("email_code");
	}

	public M setEmailIsveri(java.lang.Integer emailIsveri) {
		set("email_isveri", emailIsveri);
		return (M)this;
	}
	
	public java.lang.Integer getEmailIsveri() {
		return getInt("email_isveri");
	}

	public M setEmailDates(java.util.Date emailDates) {
		set("email_dates", emailDates);
		return (M)this;
	}
	
	public java.util.Date getEmailDates() {
		return get("email_dates");
	}

}
