package com.ccc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUserEmail(java.lang.String userEmail) {
		set("user_email", userEmail);
		return (M)this;
	}

	public java.lang.String getUserEmail() {
		return getStr("user_email");
	}

	public M setUserPass(java.lang.String userPass) {
		set("user_pass", userPass);
		return (M)this;
	}

	public java.lang.String getUserPass() {
		return getStr("user_pass");
	}

	public M setUserNickname(java.lang.String userNickname) {
		set("user_nickname", userNickname);
		return (M)this;
	}

	public java.lang.String getUserNickname() {
		return getStr("user_nickname");
	}

	public M setUserAuth(java.lang.Integer userAuth) {
		set("user_auth", userAuth);
		return (M)this;
	}

	public java.lang.Integer getUserAuth() {
		return getInt("user_auth");
	}

	public M setUserPic(java.lang.String userPic) {
		set("user_pic", userPic);
		return (M)this;
	}

	public java.lang.String getUserPic() {
		return getStr("user_pic");
	}

	public M setUserTel(java.lang.String userTel) {
		set("user_tel", userTel);
		return (M)this;
	}

	public java.lang.String getUserTel() {
		return getStr("user_tel");
	}

	public M setUserAuto(java.lang.String userAuto) {
		set("user_auto", userAuto);
		return (M)this;
	}

	public java.lang.String getUserAuto() {
		return getStr("user_auto");
	}

	public M setUserSex(java.lang.Integer userSex) {
		set("user_sex", userSex);
		return (M)this;
	}

	public java.lang.Integer getUserSex() {
		return getInt("user_sex");
	}

	public M setUserHome(java.lang.String userHome) {
		set("user_home", userHome);
		return (M)this;
	}

	public java.lang.String getUserHome() {
		return getStr("user_home");
	}

	public M setUserBirthday(java.lang.String userBirthday) {
		set("user_birthday", userBirthday);
		return (M)this;
	}

	public java.lang.String getUserBirthday() {
		return getStr("user_birthday");
	}

	public M setUserDates(java.util.Date userDates) {
		set("user_dates", userDates);
		return (M)this;
	}

	public java.util.Date getUserDates() {
		return get("user_dates");
	}

	public M setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
		return (M)this;
	}

	public java.lang.String getUserCode() {
		return getStr("user_code");
	}

}
