package com.ccc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePic<M extends BasePic<M>> extends Model<M> implements IBean {

	public M setPicId(java.lang.Integer picId) {
		set("pic_id", picId);
		return (M)this;
	}
	
	public java.lang.Integer getPicId() {
		return getInt("pic_id");
	}

	public M setPicType(java.lang.Integer picType) {
		set("pic_type", picType);
		return (M)this;
	}
	
	public java.lang.Integer getPicType() {
		return getInt("pic_type");
	}

	public M setPicHtmlType(java.lang.String picHtmlType) {
		set("pic_html_type", picHtmlType);
		return (M)this;
	}
	
	public java.lang.String getPicHtmlType() {
		return getStr("pic_html_type");
	}

	public M setPicTypeName(java.lang.String picTypeName) {
		set("pic_type_name", picTypeName);
		return (M)this;
	}
	
	public java.lang.String getPicTypeName() {
		return getStr("pic_type_name");
	}

	public M setPicHtmlGraphUrl(java.lang.String picHtmlGraphUrl) {
		set("pic_html_graph_url", picHtmlGraphUrl);
		return (M)this;
	}
	
	public java.lang.String getPicHtmlGraphUrl() {
		return getStr("pic_html_graph_url");
	}

	public M setPicFileUrl(java.lang.String picFileUrl) {
		set("pic_file_url", picFileUrl);
		return (M)this;
	}
	
	public java.lang.String getPicFileUrl() {
		return getStr("pic_file_url");
	}

	public M setPicIp(java.lang.String picIp) {
		set("pic_ip", picIp);
		return (M)this;
	}
	
	public java.lang.String getPicIp() {
		return getStr("pic_ip");
	}

	public M setPicAuto(java.lang.String picAuto) {
		set("pic_auto", picAuto);
		return (M)this;
	}
	
	public java.lang.String getPicAuto() {
		return getStr("pic_auto");
	}

	public M setPicHot(java.lang.Integer picHot) {
		set("pic_hot", picHot);
		return (M)this;
	}
	
	public java.lang.Integer getPicHot() {
		return getInt("pic_hot");
	}

	public M setPicDates(java.util.Date picDates) {
		set("pic_dates", picDates);
		return (M)this;
	}
	
	public java.util.Date getPicDates() {
		return get("pic_dates");
	}

	public M setPicAuthor(java.lang.Integer picAuthor) {
		set("pic_author", picAuthor);
		return (M)this;
	}
	
	public java.lang.Integer getPicAuthor() {
		return getInt("pic_author");
	}

}
