package com.ccc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseType<M extends BaseType<M>> extends Model<M> implements IBean {

	public M setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
		return (M)this;
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public M setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
		return (M)this;
	}
	
	public java.lang.String getTypeName() {
		return getStr("type_name");
	}

	public M setTypeLevel(java.lang.Integer typeLevel) {
		set("type_level", typeLevel);
		return (M)this;
	}
	
	public java.lang.Integer getTypeLevel() {
		return getInt("type_level");
	}

	public M setTypeHot(java.lang.Integer typeHot) {
		set("type_hot", typeHot);
		return (M)this;
	}
	
	public java.lang.Integer getTypeHot() {
		return getInt("type_hot");
	}

	public M setTypeDates(java.util.Date typeDates) {
		set("type_dates", typeDates);
		return (M)this;
	}
	
	public java.util.Date getTypeDates() {
		return get("type_dates");
	}

}
