package com.ccc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePost<M extends BasePost<M>> extends Model<M> implements IBean {

	public M setPostId(java.lang.Integer postId) {
		set("post_id", postId);
		return (M)this;
	}
	
	public java.lang.Integer getPostId() {
		return getInt("post_id");
	}

	public M setPostType(java.lang.Integer postType) {
		set("post_type", postType);
		return (M)this;
	}
	
	public java.lang.Integer getPostType() {
		return getInt("post_type");
	}

	public M setPostTitle(java.lang.String postTitle) {
		set("post_title", postTitle);
		return (M)this;
	}
	
	public java.lang.String getPostTitle() {
		return getStr("post_title");
	}

	public M setPostContent(java.lang.String postContent) {
		set("post_content", postContent);
		return (M)this;
	}
	
	public java.lang.String getPostContent() {
		return getStr("post_content");
	}

	public M setPostAuthor(java.lang.Integer postAuthor) {
		set("post_author", postAuthor);
		return (M)this;
	}
	
	public java.lang.Integer getPostAuthor() {
		return getInt("post_author");
	}

	public M setPostPlate(java.lang.Integer postPlate) {
		set("post_plate", postPlate);
		return (M)this;
	}
	
	public java.lang.Integer getPostPlate() {
		return getInt("post_plate");
	}

	public M setPostView(java.lang.Integer postView) {
		set("post_view", postView);
		return (M)this;
	}
	
	public java.lang.Integer getPostView() {
		return getInt("post_view");
	}

	public M setPostPic(java.lang.String postPic) {
		set("post_pic", postPic);
		return (M)this;
	}
	
	public java.lang.String getPostPic() {
		return getStr("post_pic");
	}

	public M setPostMpic(java.lang.String postMpic) {
		set("post_mpic", postMpic);
		return (M)this;
	}
	
	public java.lang.String getPostMpic() {
		return getStr("post_mpic");
	}

	public M setPostAuto(java.lang.String postAuto) {
		set("post_auto", postAuto);
		return (M)this;
	}
	
	public java.lang.String getPostAuto() {
		return getStr("post_auto");
	}

	public M setPostHot(java.lang.Integer postHot) {
		set("post_hot", postHot);
		return (M)this;
	}
	
	public java.lang.Integer getPostHot() {
		return getInt("post_hot");
	}

	public M setPostPlace(java.lang.String postPlace) {
		set("post_place", postPlace);
		return (M)this;
	}
	
	public java.lang.String getPostPlace() {
		return getStr("post_place");
	}

	public M setPostUrl(java.lang.String postUrl) {
		set("post_url", postUrl);
		return (M)this;
	}
	
	public java.lang.String getPostUrl() {
		return getStr("post_url");
	}

	public M setPostCommNum(java.lang.Integer postCommNum) {
		set("post_comm_num", postCommNum);
		return (M)this;
	}
	
	public java.lang.Integer getPostCommNum() {
		return getInt("post_comm_num");
	}

	public M setPostSeeNum(java.lang.Integer postSeeNum) {
		set("post_see_num", postSeeNum);
		return (M)this;
	}
	
	public java.lang.Integer getPostSeeNum() {
		return getInt("post_see_num");
	}

	public M setPostDates(java.util.Date postDates) {
		set("post_dates", postDates);
		return (M)this;
	}
	
	public java.util.Date getPostDates() {
		return get("post_dates");
	}

}
