package com.ccc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseParts<M extends BaseParts<M>> extends Model<M> implements IBean {

	public M setPartsId(java.lang.Integer partsId) {
		set("parts_id", partsId);
		return (M)this;
	}
	
	public java.lang.Integer getPartsId() {
		return getInt("parts_id");
	}

	public M setPartsHot(java.lang.Integer partsHot) {
		set("parts_hot", partsHot);
		return (M)this;
	}
	
	public java.lang.Integer getPartsHot() {
		return getInt("parts_hot");
	}

	public M setPartsTitle(java.lang.String partsTitle) {
		set("parts_title", partsTitle);
		return (M)this;
	}
	
	public java.lang.String getPartsTitle() {
		return getStr("parts_title");
	}

	public M setPartsUrl(java.lang.String partsUrl) {
		set("parts_url", partsUrl);
		return (M)this;
	}
	
	public java.lang.String getPartsUrl() {
		return getStr("parts_url");
	}

	public M setPartsHeadSrc(java.lang.String partsHeadSrc) {
		set("parts_head_src", partsHeadSrc);
		return (M)this;
	}
	
	public java.lang.String getPartsHeadSrc() {
		return getStr("parts_head_src");
	}

	public M setPartsPicUrl(java.lang.String partsPicUrl) {
		set("parts_pic_url", partsPicUrl);
		return (M)this;
	}
	
	public java.lang.String getPartsPicUrl() {
		return getStr("parts_pic_url");
	}

	public M setPartsAuto(java.lang.String partsAuto) {
		set("parts_auto", partsAuto);
		return (M)this;
	}
	
	public java.lang.String getPartsAuto() {
		return getStr("parts_auto");
	}

	public M setPartsContent(java.lang.String partsContent) {
		set("parts_content", partsContent);
		return (M)this;
	}
	
	public java.lang.String getPartsContent() {
		return getStr("parts_content");
	}

	public M setPartsDate(java.lang.String partsDate) {
		set("parts_date", partsDate);
		return (M)this;
	}
	
	public java.lang.String getPartsDate() {
		return getStr("parts_date");
	}

	public M setPartsDates(java.util.Date partsDates) {
		set("parts_dates", partsDates);
		return (M)this;
	}
	
	public java.util.Date getPartsDates() {
		return get("parts_dates");
	}

	public M setPartsPlate(java.lang.Integer partsPlate) {
		set("parts_plate", partsPlate);
		return (M)this;
	}
	
	public java.lang.Integer getPartsPlate() {
		return getInt("parts_plate");
	}

	public M setPartsAuthor(java.lang.Integer partsAuthor) {
		set("parts_author", partsAuthor);
		return (M)this;
	}
	
	public java.lang.Integer getPartsAuthor() {
		return getInt("parts_author");
	}

}
