package com.ccc.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("email", "email_id", Email.class);
		arp.addMapping("info", "info_id", Info.class);
		arp.addMapping("parts", "parts_id", Parts.class);
		arp.addMapping("post", "post_id", Post.class);
		arp.addMapping("type", "type_id", Type.class);
		arp.addMapping("user", "user_id", User.class);
		arp.addMapping("comment", "comment_id", Comment.class);
		arp.addMapping("pic", "pic_id", Pic.class);
	}
}

