package com.ccc.common.model;

import com.ccc.common.model.base.BaseEmail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Email extends BaseEmail<Email> {
	public static final Email dao = new Email().dao();
}
