package com.ccc.common.model;

import com.ccc.common.model.base.BaseParts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Parts extends BaseParts<Parts> {
	public static final Parts dao = new Parts().dao();
}
