package com.ccc.common.model;

import com.ccc.common.model.base.BasePic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pic extends BasePic<Pic> {
	public static final Pic dao = new Pic().dao();
}
