package com.ccc.common.model;

import java.util.Arrays;
import java.util.List;

import com.ccc.common.model.base.BasePost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Post extends BasePost<Post> {
	public static final Post dao = new Post().dao();

	private List<String> img;

	public List<String> getImg() {
		
		if (img == null) {
			setImg();
		}

		return img;
	}

	public void setImg() {

		if (getPostMpic() == null)
			return;

		img = Arrays.asList(getPostMpic().split(","));

	}

}
