package com.ccc.common.model;

import com.ccc.common.model.base.BaseUser;
import com.jfinal.kit.StrKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User().dao();

    private String pic;

    public String getPic() {
        if (StrKit.isBlank(pic)) {
            pic = StrKit.isBlank(getUserPic()) ? "/fronts/images/co.png" : getUserPic();
        }
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }
}
